---
- name: "Putty | Install package"
  tags: laptop
  ansible.builtin.apt:
    name: putty
    state: latest
  become: true

- name: "Putty | Copy sessions"
  tags: laptop
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/putty/sessions/"
  with_fileglob: "{{ role_path }}/files/sessions/*"

- name: "Putty | Create symlink"
  tags: laptop
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.config/putty"
    dest: "{{ ansible_user_dir }}/.putty"
    state: link
    force: true
