---
- name: "Bash | Check if first run"
  stat:
    path: "{{ first_run }}"
  register: first_run

- name: "Bash | Create backup directory"
  ansible.builtin.file:
   path: "{{ backup_dir }}"
   state: directory
   mode: '0755'
  when: first_run.stat.islnk is not defined 

- name: "Bash | Check if files exist"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/{{ item }}"
  with_items: "{{ old_dotfiles }}"
  register: stat_results

#- name: "Bash | Debug stat results"
#  debug:
#    msg: "{{ stat_results }}"

- name: "Bash | Copy old dotfiles"
  ansible.builtin.copy:
    src: "{{ item.stat.path }}"
    dest: "{{ backup_dir }}"
  loop: "{{ stat_results.results }}"
  when: item.stat.exists == True and first_run.stat.islnk is not defined
  loop_control:
    label: "{{ item.item }}"

- name: "Bash | Create symlinks"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item | basename }}"
    state: link
    force: true
  with_fileglob: "files/*"

- name: "Bash | Create symlink for now script"
  ansible.builtin.file:
    src: "{{ role_path}}/files/scripts/{{ now_script }}"
    dest: "{{ ansible_user_dir }}/bin/{{ now_script }}"
    state: link
    force: true

- name: "Bash | Make 'now' script executable"
  ansible.builtin.file:
    path: "{{ role_path}}/files/scripts/{{ now_script }}"
    mode: '0700'
