---
- name: "Bash | Check if first run"
  stat:
    path: "{{ first_run }}"
  register: first_run

- name: "Bash | Create backup directory"
  ansible.builtin.file:
   path: "{{ backup_dir }}"
   state: directory
   mode: '0755'
  when: first_run.stat.islnk is not defined 

- name: "Bash | Check if files exist"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/{{ item }}"
  with_items: "{{ old_dotfiles }}"
  register: stat_result

- name: Ansible
  debug:
    msg: "{{ stat_result }}"

#- name: Temp test
#  ansible.builtin.copy:
#    src: "{{ ansible_user_dir }}/{{ item }}"
#    dest: "{{ backup_dir }}"
#  with_items: "{{ old_dotfiles }}"
#  when: stat_result.item.name == item and stat_result.item.stat.exists == True

- name: "Bash | Copy old dotfiles"
  ansible.builtin.copy:
    src: "{{ item.stat.path }}"
    dest: "{{ backup_dir }}"
  #  with_items: "{{ stat_result.results }}"
  loop: "{{ stat_result.results }}"
  when: item.stat.exists == True
  #  loop_control:
  #    label: "{{ item.name }}"

#- name: "Bash | Create symlinks"
#  ansible.builtin.file:
#    src: "{{ item }}"
#    dest: "{{ ansible_user_dir }}/.{{ item | basename }}"
#    state: link
#    force: true
#  with_fileglob: "files/*"
