---
- name: "Bash | Check if first run"
  stat:
    path: "{{ first_run }}"
  register: first_run

- name: "Bash | Create backup directory"
  ansible.builtin.file:
   path: "{{ backup_dir }}"
   state: directory
   mode: '0755'
  when: first_run.stat.islnk is not defined 

- name: "Bash | Copy old dotfiles to backup directory"
  ansible.builtin.copy:
    src: "{{ ansible_user_dir }}/{{ item }}"
    dest: "{{ backup_dir }}"
    remote_src: yes
  with_items: "{{ old_dotfiles }}"
  when: first_run.stat.islnk is not defined 

- name: "Bash | Create symlinks"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    state: link
    force: true
  with_items: "files/*"

