---
- hosts: all 
  become: false
  pre_tasks:

    - name: install updates
      become: true
      tags: always
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'yes'
      changed_when: false

- hosts: laptop
  become: false
  tasks:

    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or core_roles + laptop_roles | default([]) | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always

    - name: Create symlink to dotfiles script"
      ansible.builtin.file:
          src: "{{ ansible_user_dir }}/.dotfiles/bin/dotfiles"
          dest: "{{ ansible_user_dir }}/bin/dotfiles"
          state: link
          force: true

