---
#--- VirtualBox Edition ---#

virtualbox_edition: latest-stable

#--- VirtualBox repos ---#

virtualbox_repo_deb_key:
  - https://www.virtualbox.org/download/oracle_vbox.asc
  - https://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc

virtualbox_repo_rpm_key: https://www.virtualbox.org/download/oracle_vbox.asc

virtualbox_url_prefix: 'https://download.virtualbox.org/virtualbox'

virtualbox_url_version: '{{ virtualbox_url_prefix }}/{{ virtualbox_edition | upper }}.TXT'

virtualbox_url_path_to_files: '{{ virtualbox_url_prefix }}/{{ virtualbox_available_version_fact }}'

virtualbox_checksum_file_url: '{{ virtualbox_url_path_to_files }}/{{ virtualbox_checksum_algorithm | upper }}SUMS'

virtualbox_windows_local_download_path: '{{ ansible_env.TMP }}\virtualbox'

virtualbox_install_extension_pack: true
# virtualbox_install_extension_pack: false

virtualbox_checksum_algorithm: sha256
# virtualbox_checksum_algorithm: md5

virtualbox_version: latest
# virtualbox_version: 5.2.38

# If you *NOT* use apt-cacher-ng or other caching proxy - select "https".
http_or_https: http
# http_or_https: https
