---
- name: "Nala | Install package"
  tags: laptop
  ansible.builtin.apt:
    name: nala
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version != '20.04'
