---
- name: "SSH | Install package"
  ansible.builtin.pacman:
    name:
      - openssh
    state: present
  become: true

- name: "SSH | Enable and start sshd service"
  ansible.builtin.systemd_service:
    name: sshd
    enabled: true
    state: started
    masked: no

- name: "SSH | Ensure {{ ansible_user_dir }}/.ssh directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
  become: false

- name: "SSH | Copy SSH keys"
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: 0600
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"
