---
- name: "Git | Install package"
  tags: laptop
  ansible.builtin.apt:
    name: git
    state: latest
  become: true

- name: "Git | Change remote origin"
  community.general.git_config:
    repo: "{{ ansible_user_dir }}/.dotfiles/"
    scope: 'local'
    name: 'remote.origin.url'
    value: 'git@github.com:mpboden/ansible.git'
