---
- name: Get facts about Extension Pack 4 Linux
  when:
    - ansible_system == 'Linux'
  become: yes
  shell: VBoxManage list extpacks | sed 's/^/  / ; s/  Extension/- Extension/'
  register: vboxmanage_list_extpacks_linux
  changed_when: vboxmanage_list_extpacks_linux.rc != 0

- name: Set facts about Extension Pack
  vars:
    plugobj:
      plugkey: plugvalue
  set_fact:
    virtualbox_installed_extpack_info_linux_fact:
      "{{ vboxmanage_list_extpacks_linux.stdout
      | from_yaml
      | default(plugobj) }}"

- set_fact:
    virtualbox_installed_extpack_info_fact:
      "{{ virtualbox_installed_extpack_info_fact 
      | default({})
      | combine(virtualbox_installed_extpack_info_linux_fact) }}"

- set_fact:
    virtualbox_full_installed_extpack_version_fact:
      "{{ virtualbox_installed_extpack_info_fact['Version'] }}.{{ virtualbox_installed_extpack_info_fact['Revision'] }}"
  when: virtualbox_installed_extpack_info_fact['Extension Packs'] != 0

#---

- name: Download VirtualBox Extension Pack 4 Linux
  when:
    - ansible_system == 'Linux'
    - virtualbox_installed_extpack_info_fact['Extension Packs'] == 0
      or
      virtualbox_full_installed_extpack_version_fact != virtualbox_full_available_extpack_version_fact
  become: yes
  get_url:
    url: '{{ virtualbox_extpack_direct_download_url_fact }}'
    dest: '/tmp/{{ virtualbox_available_extpack_filename_fact }}'
    checksum: '{{ virtualbox_checksum_algorithm }}:{{ virtualbox_available_extpack_checksum_fact }}'
