---
- name: Get VirtualBox available version
  uri:
    url: '{{ virtualbox_url_version }}'
    return_content: yes
  delegate_to: localhost
  register: virtualbox_available_version

#---

- name: Set facts about available virtualbox version part 1
  block:
    - set_fact:
        virtualbox_available_version_fact:
          "{{ virtualbox_available_version.content | trim }}"
    - set_fact:
        virtualbox_available_major_and_minor_version_fact:
          "{{ virtualbox_available_version_fact.split('.', 2)[:-1] | join('.') }}"

#---

- name: Get VirtualBox checksum content
  uri:
    url: '{{ virtualbox_checksum_file_url }}'
    return_content: yes
  register: virtualbox_checksum_file_content
  delegate_to: localhost

#---

- name: Set facts about available virtualbox version part 2
  vars:
    virtualbox_extpack_direct_download_url_var:
      "{{ virtualbox_url_path_to_files + '/' + virtualbox_available_extpack_filename_fact }}"
  block:
    - set_fact:
        virtualbox_available_extpack_filename_fact:
          '{{ (virtualbox_checksum_file_content.content
          | regex_findall(".*vbox-extpack"))[0].split("*")[1] }}'
    - set_fact:
        virtualbox_available_extpack_checksum_fact:
          '{{ (virtualbox_checksum_file_content.content
          | regex_findall(".*vbox-extpack"))[0].split("*")[0] | trim }}'
    - set_fact:
        virtualbox_available_private_version_fact:
          '{{ virtualbox_available_extpack_filename_fact.split("-")[2].split(".")[0] }}'
    - set_fact:
        virtualbox_full_available_version_fact:
          '{{ virtualbox_available_version_fact }}.{{ virtualbox_available_private_version_fact }}'
    - set_fact:
        virtualbox_full_available_extpack_version_fact:
          '{{ virtualbox_full_available_version_fact }}'
    - set_fact:
        virtualbox_extpack_direct_download_url_fact:
          "{{ virtualbox_extpack_direct_download_url
          | default(virtualbox_extpack_direct_download_url_var) }}"

#---

- name: Get VirtualBox bin status 4 Linux
  when: ansible_system == 'Linux'
  stat:
    path: /usr/bin/VBoxManage
  register: virtualbox_bin

#---

# https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html
#- debug:
#    msg: "{{ hostvars }}"
