# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,exports,bash_prompt,aliases,functions,extra};
	do
		[ -r "$file" ] && [ -f "$file" ] && source "$file";
	done;
unset file;

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar;
	do
		shopt -s "$option" 2> /dev/null;
	done;
now

ssh-add -l &>/dev/null
ID_GITHUB="$HOME/.ssh/id_github_mike"
if [ "$?" -lt 2 ] && [ -f "$ID_GITHUB" ]; then
    ssh-add -q $ID_GITHUB
fi

OS=$(cat /etc/os-release | grep NAME | head -n 1 | awk -F\" '{print $2}')

if [[ "$OS" == "Arch"* ]]; then
    source /usr/share/fzf/key-bindings.bash
    source /usr/share/fzf/completion.bash
else
    source /usr/share/doc/fzf/examples/key-bindings.bash
    source /usr/share/doc/fzf/examples/completion.bash
fi
