---
- name: "Neovim | Install Dependencies"
  ansible.builtin.pacman:
    name:
      - npm
      - ansible-lint
      - ripgrep
      - xclip
      - unzip
    state: present
  become: true

- name: "Neovim | Install Package"
  ansible.builtin.pacman:
    name:
      - neovim
    state: present
  become: true

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
  become: false

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

