---
- name: "Neovim | Dependencies"
  ansible.builtin.apt:
    name:
      - npm
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - xclip
    state: present
  become: true

- name: "Neovim | Add repository" 
  apt_repository: repo="ppa:neovim-ppa/stable" state=present
  become: true

- name: "Neovim | Create a directory if it does not exist"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/bin"
    state: directory
    mode: '0755'
    
- name: "Neovim | Unarchive a file that needs to be downloaded (added in 2.0)"
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: "{{ ansible_user_dir }}/bin"
    remote_src: yes

- name: "Neovim | Create symlink to nvim"
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/bin/nvim-linux64/bin/nvim"
    dest: "{{ ansible_user_dir }}/bin/nvim"
    state: link
    force: true

- name: "Neovim | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

